[env:esp32-c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    bblanchon/ArduinoJson@^7.0.4

[env:native]
platform = native
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    throwtheswitch/Unity@^2.5.2
build_flags = -std=gnu++17 -DUNITY_INCLUDE_DOUBLE
test_framework = unity
test_build_src = true
